### ISSUE TITLE
mariadb container

### ISSUE THREAD

**Issue by ghost** [shiver/docker-mail#1]
Hi

Can i link db to mariadb container instead postgres?
i work with Dokkualt + Mariadb

Thaks

**Comment by shiver** [comment]
Apologies for the late reply.
Most definitely possible to work with MariaDB instead, but unfortunately all the setup scripts currently expect Postgres. 
It probably wouldn't take too much effort to make MariaDB/MySQL an option, but unfortunately I am a bit busy with work at the moment.

Hopefully I can get to it in the not too distant future.
